apiVersion: v1
data:
  MARIADB_DATABASE: bW9vZGxlX2Ri
  MARIADB_PASSWORD: bW9vZGxlX3Bhc3N3b3Jk
  MARIADB_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MARIADB_USER: bW9vZGxlX3VzZXI=
kind: Secret
metadata:
  creationTimestamp: null
  name: mariadb-secret